pipeline {
    agent any
    
    stages {
        stage('Update') {
            steps {
                script {
                    // Instalar dependencias del frontend
                    bat "cd T1_T2_Recetario_CI_CD/frontend && npm install"
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Iniciar frontend en modo desarrollo en segundo plano
                    bat "cd T1_T2_Recetario_CI_CD/frontend && npm run start &"
                    // Esperar a que el servidor esté listo
                    waitUntil { 
                        def response = sh(script: "curl -Is http://localhost:4200 | head -n 1", returnStatus: true)
                        return response == 0
                    }
                    // Ejecutar pruebas de selenium
                    bat "cd T1_T2_Recetario_CI_CD/selenium_project/RecetarioTest && mvn clean test"
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    // Compilar el frontend
                    bat "cd T1_T2_Recetario_CI_CD/frontend && npm run build"
                }
            }
        }
        stage('Deploy') {
            steps {
                // Copiar los archivos compilados al directorio de despliegue
                bat 'xcopy "T1_T2_Recetario_CI_CD/frontend/dist" "C:/xampp/htdocs" /s/y'
            }
        }
    }
}
