pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    // Instalar dependencias del frontend
                    bat "cd frontend && npm install"
                    // Compilar el frontend
                    bat "cd frontend && npm run build"
                }
            }
        }
        stage('Deploy') {
            steps {
                // Copiar los archivos compilados al directorio de despliegue
                bat 'xcopy "frontend/dist" "C:/xampp/htdocs" /s/y'
            }
        }
    }
}
